# Generated by Django 6.0.7 on 2026-09-27 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("Essential", "Essential"),
                    ("Discretionary", "Discretionary"),
                    ("Income", "Income"),
                ],
                default="Discretionary",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("user", "category", "month", "year")},
        ),
    ]
