# Generated by Django 6.0.7 on 2026-10-07 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_category_category_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aichathistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="aichathistory",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Assistant"), ("model", "AI")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="aichathistory",
            name="session_id",
            field=models.CharField(db_index=True, default="default", max_length=100),
        ),
    ]
